name: Android Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 设置JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    # 添加这一步 - 创建空的google-services.json文件
    - name: 创建Google Services配置
      run: |
        echo '{"project_info":{"project_id":"dummy-project","project_number":"123456789","name":"DummyProject"},"client":[{"client_info":{"mobilesdk_app_id":"1:123456789:android:1234567890abcdef"}}]}' > app/google-services.json
      
    - name: 授予Gradle执行权限
      run: chmod +x ./gradlew
    
    - name: 构建Debug APK
      run: ./gradlew assembleDebug --stacktrace
    
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
